version: '3.8'

services:
  open-stocks-mcp-dev:
    # Build from source for development with HTTP transport
    build:
      context: ../../  # Build from project root
      dockerfile: examples/Docker/Dockerfile.dev
    # Name the container for easier identification
    container_name: open-stocks-mcp-server-dev
    # Restart the container automatically if it stops
    restart: unless-stopped
    # Pass environment variables from a .env file in the same directory
    # This is the recommended way to handle sensitive data like credentials
    env_file:
      - .env
    # Map the container's port 3000 to the host's port 3000 (HTTP transport)
    ports:
      - "3000:3000"
    # Health check configuration for HTTP transport
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    # Security configuration
    user: "1001:1001"  # Run as non-root user
    # Resource limits (optional but recommended for production)
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    # Define the command to run the application
    # This overrides any CMD in the base Dockerfile
    command: >
      open-stocks-mcp-server
      --transport http
      --host 0.0.0.0
      --port 3000
    # Add logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Volume mount for development (optional)
    volumes:
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 100M

# Note:
# This is the development version that builds from source
# For production, use docker-compose.yml with the published package