apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-stocks-mcp-tokens
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-stocks-mcp-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
